export {default as Announcementbar} from './Announcementbar';
export {default as Navbar} from './Navbar';
export {default as HeroSection} from './HeroSection';
export {default as Logocloud} from './Logocloud';
export {default as Feature} from './Feature'
export {default as Feature2} from './Feature2'
export {default as Component1} from './Component1'
export {default as Testimonial} from './Testimonial'
export {default as CalltoAction} from './CalltoAction'
export {default as Footer} from './Footer'
export {default as Email} from './Email'